### ISSUE TITLE
在 node 0.11.x 下，build失败了

### ISSUE THREAD

**Issue by vfasky** [aszxqw/nodejieba#11]
```sh
npm WARN engine nodejieba@0.2.5: wanted: {"node":"0.10.x"} (current: {"node":"0.11.13","npm":"2.1.5"})
\
> nodejieba@0.2.5 install /Users/vfasky/git/kotenei/node_modules/nodejieba
> node-gyp rebuild

  CXX(target) Release/obj.target/segment/src/segment.o
In file included from ../src/segment.cpp:1:
In file included from ../src/mix_segment.h:3:
../src/utils.h:16:24: error: cannot initialize a parameter of type
      'v8::Isolate *' with an rvalue of type 'size_type' (aka 'unsigned long')
    array = Array::New(ov.size());
                       ^~~~~~~~~
/Users/vfasky/.node-gyp/0.11.13/deps/v8/include/v8.h:2486:36: note: passing
      argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
In file included from ../src/segment.cpp:1:
In file included from ../src/mix_segment.h:3:
../src/utils.h:18:31: error: no member named 'New' in 'v8::String'
        array->Set(i, String::New(ov[i].c_str()));
                      ~~~~~~~~^
../src/utils.h:23:24: error: cannot initialize a parameter of type
      'v8::Isolate *' with an rvalue of type 'size_type' (aka 'unsigned long')
    array = Array::New(ov.size());
                       ^~~~~~~~~
/Users/vfasky/.node-gyp/0.11.13/deps/v8/include/v8.h:2486:36: note: passing
      argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
In file included from ../src/segment.cpp:1:
In file included from ../src/mix_segment.h:3:
../src/utils.h:25:31: error: no member named 'New' in 'v8::String'
        array->Set(i, String::New((ov[i].first + ":" + ov[i].second).c_str()));
                      ~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/segment/src/segment.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vfasky/git/kotenei/node_modules/nodejieba
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/vfasky/.cnpmrc" "--disturl=https://npm.taobao.org/dist" "--cache=/Users/vfasky/.npm/.cache_cnpm" "--registry=https://registry.npm.taobao.org" "install" "nodejieba"
npm ERR! node v0.11.13
npm ERR! npm  v2.1.5
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@0.2.5 install script.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vfasky/git/kotenei/npm-debug.log
```

**Comment by aszxqw** [comment]
恩，确实是有这个问题，node的扩展开发，兼容性一直是个问题我，最近我尝试着修复修复吧。

**Comment by aszxqw** [comment]
@vfasky  谢谢你的反馈，刚刚提交的最新版本 0.2.6 已经修复该兼容性问题。你可以试试看看，有任何问题欢迎反馈 ：）

**Comment by vfasky** [comment]
在 v0.11.13 安装成功了， 感谢 ^_^
